import { Inter } from 'next/font/google'
import Header from '@/components/Header/Headercomponents'
import Navigation from '@/components/Navigation/Navigationcomponents'
import Products from '@/components/Products/Productscomponents'
import SideBar from '@/components/SideBar/SideBarcomponents'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Header />
        <Navigation />
        <div className='container-fluid mt-5'>
          <div className='flex '>
            <div className='lg:w-2/12 md:w-2/12 sm:w-2/12 p-3 border text-dark hidden md:block'>
              <SideBar/>
            </div>
            <div className='lg:w-10/12 md:w-10/12 sm:w-10/12 md:pl-4'>
              <Products />
            </div>
          </div>
       </div>
      </body>
    </html>
  )
}
