'use client'
import { Inter } from 'next/font/google'
import Main from '@/components/maincomponents'
import SiteProvider from '../context/SiteContext'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <SiteProvider>
        <Main />
       </SiteProvider>
      </body>
    </html>
  )
}
